### ISSUE TITLE
E911 Module

### ISSUE THREAD

**Issue by demonspork** [samael33/fusionpbx#2]
I am also using voipinnovations and was trying to see if your E911 module would be useful for us, and was wondering if you might provide some basic instructions to use it. I attempted to set it up but have been unable to get it working myself. My PHP skills are pretty basic, so I am probably missing/misinterpreting a variable that I need to set to make that app work.

**Comment by igorolhovskiy** [comment]
Hi!
This app was mostly written for users can register their own DID's in VoipInnovations in their e911 service.
As of now, it uses several variables to integrate with voipinnovations
<img width="1587" alt="screenshot at oct 15 10-52-31" src="https://user-images.githubusercontent.com/11504195/46937266-810c2380-d069-11e8-8b72-55963911e1ad.png">

**Comment by demonspork** [comment]
Thanks for replying. I was only missing the did_length variable, but I still don't have it working. When I attempt to add a registration it just says "Not Validated" and when I use the "Load From Server" button it just goes to a page saying:

Please provide: Please provide: CityPlease provide: StatePlease provide: ZIP codePlease provide: Callername

even though that information is provided, I assume it says that because it wasn't able to retrieve the information from the API?


![image](https://user-images.githubusercontent.com/432305/46940719-045c5380-d02f-11e8-9b89-9a8ba225c5e9.png)

**Comment by igorolhovskiy** [comment]
At this point, I'd debug queries and answers from voipinnovations service.
Really, this app/scenario was done and tested only on 1 working environment.

**Comment by demonspork** [comment]
Thanks for the info. I will probably keep my eye out if you do some more improvements/feature additions to the app, but for now, I will readily admit that is out of my wheelhouse without more time investment than it is probably worth for me. It will eventually become worth it to brush up on PHP and dive in, but not today.

Thanks for making this and publishing it, I will definitely be making use of it (and the API call examples) in the future!

**Comment by demonspork** [comment]
Ahahah, scratch that. I started digging in, found some commented code that looks like it is supposed to write the API calls to a log file (it doesn't work), but everything else magically started working. I had just re-done the API user and secrets so that is probably the actual cause.

After playing with it for a few minutes, my to-do list contains:
1. Form to Bulk Apply Emergency Caller ID Numbers to extensions (maybe even mark the ones with an unprovisioned number assigned in that field)
2. Master "Update From Server" button to check the status of all DIDs at once.
3. Use DID Groups or Customers feature in VI portal to populate a drop-down menu of assigned DIDs to fill in destinations/E911 details (this might end up just in its own app, like "VI Tools")

I will definitely make sure to fork and let you know if I get anything half-way usable along these lines. My eventual goal is to allow our techs to rely entirely on the FusionPBX interface and not even need a VI login at all.
